version: "3.0"

services:
    neo4j-service:
        image: neo4j:4.2.9-enterprise
        ports:
            - 7474:7474
            - 7687:7687
            - 6362:6362
        environment:
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_AUTH: neo4j/test
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
        volumes:
            - "neo-data:/data"
            - "neo-data:/conf"
            - "neo-data:/plugins"
            - "neo-data:/import"
            - "neo-data:/logs"
        healthcheck:
            test: wget http://localhost:7474/browser -O -
            interval: 1s
            timeout: 1s
            retries: 40
    # tests:
    #     build:
    #         context: .
    #     environment:
    #         - NEO_URL=neo4j://neo4j-service:7687
    #         - NEO_USER=neo4j
    #         - NEO_PASSWORD=test
    #     depends_on:
    #         neo4j-service:
    #             condition: service_healthy

volumes:
  neo-data: